# Generated by Django 5.1.6 on 2025-03-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('make_date', models.DateField(auto_now_add=True)),
                ('id_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='apiapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_date', models.DateField(auto_now_add=True)),
                ('progress', models.FloatField(default=0)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='apiapp.client')),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_courses', to='apiapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.IntegerField()),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='apiapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_information', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='blocks/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='blocks/videos/')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='apiapp.module')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_question', models.TextField()),
                ('id_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiapp.block')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_answer', models.TextField()),
                ('is_true', models.BooleanField(default=False)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='apiapp.question')),
            ],
        ),
    ]
